version: '3'

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'cs191capstone-fastapi'
    restart: unless-stopped
    expose:
      - '8000'
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
